services:
  backend:
    build:
      context: ./backend
    container_name: fullstack-backend
    environment:
      PORT: 4000
    ports:
      - '4000:4000'

  frontend:
    build:
      context: ./frontend
    container_name: fullstack-frontend
    ports:
      - '5173:80'
    depends_on:
      - backend